// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Service {
  public static partial class Import
  {
    static readonly string __ServiceName = "service.Import";

    static readonly grpc::Marshaller<global::Service.ImportRequest> __Marshaller_service_ImportRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Service.ImportRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Service.ImportResponse> __Marshaller_service_ImportResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Service.ImportResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Service.ImportRequest, global::Service.ImportResponse> __Method_Import = new grpc::Method<global::Service.ImportRequest, global::Service.ImportResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Import",
        __Marshaller_service_ImportRequest,
        __Marshaller_service_ImportResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Service.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Import</summary>
    public abstract partial class ImportBase
    {
      public virtual global::System.Threading.Tasks.Task Import(grpc::IAsyncStreamReader<global::Service.ImportRequest> requestStream, grpc::IServerStreamWriter<global::Service.ImportResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Import</summary>
    public partial class ImportClient : grpc::ClientBase<ImportClient>
    {
      /// <summary>Creates a new client for Import</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ImportClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Import that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ImportClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ImportClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ImportClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Service.ImportRequest, global::Service.ImportResponse> Import(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Import(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Service.ImportRequest, global::Service.ImportResponse> Import(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Import, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ImportClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ImportClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ImportBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Import, serviceImpl.Import).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ImportBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Import, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Service.ImportRequest, global::Service.ImportResponse>(serviceImpl.Import));
    }

  }
}
#endregion
